name: CI

# Trigger github action on pushes and pull requests to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - feature/*

jobs:
  checks:
    strategy:
      matrix:
        node-version: [18.x, 16.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Check code formatting
        run: npx prettier --check ./
        continue-on-error: true

      - name: Inform about code formatting issues
        if: ${{ failure() }}
        run: "echo 'Warning: Code formatting issues detected. Please fix them before merging the PR.'"

  build:
    needs: checks
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_ORG_ID: ${{ secrets.OPENAI_ORGANIZATION_ID }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: "Create .env file"
        run: |
          touch .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "OPENAI_ORGANIZATION_ID=${{ secrets.OPENAI_ORGANIZATION_ID }}" >> .env
          echo "WHITELISTED_USERS"="" >> .env

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

#     - name: Upload artifacts
#       uses: actions/upload-artifact@v2
#       with:
#         name: build
#         path: build/
#         retention-days: 7
