name: Prettier

on: [push, pull_request]

jobs:
  checks:
    strategy:
      matrix:
        node-version: [18.x, 16.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Check code formatting
        run: npx prettier --check ./
        continue-on-error: false
