name: Prettier

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check code formatting
        run: npx prettier --check ./
        continue-on-error: false
